# Generated by Django 3.1 on 2021-09-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_fee', models.IntegerField()),
                ('start_date', models.DateField()),
                ('duration', models.CharField(max_length=30)),
                ('trainer_name', models.CharField(max_length=30)),
                ('trainer_exp', models.CharField(max_length=20)),
            ],
        ),
    ]
